global:
  owner: quickstart-eng@amazon.com
  qsname: quickstart-openshift
  marketplace-ami: false
  reporting: true
  regions:
    - us-west-1
  cis3bucket:  s3://quickstart-ci-bucket
 
tests:
  quickstart-openshiftt1:
    template_file: quickstart-openshift.template
    parameter_input: quickstart-openshift.json
